language: r
sudo: false

install:
- R -e 'devtools::install_deps(dep = T)'

script:
- R CMD build .
- R CMD check *tar.gz

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
